In [4]:
from sqlalchemy import create_engine
from getpass import getpass

try:
    password = getpass("Introduce tu contraseña MySQL: ")
    engine = create_engine(f"mysql+pymysql://root:{password}@localhost/sakila")

    import pandas as pd
    pd.read_sql("SELECT 1", engine)

    print("Conexión realizada")

except Exception as e:
    print("Error al conectar")
    print("pruebe otra vez")

Conexión realizada

In [5]:
import pandas as pd

df = pd.read_sql("SELECT * FROM rental LIMIT 5;", engine)
df

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [6]:
# 2. Función que obtiene alquileres por mes
import pandas as pd

def rentals_month(engine, month, year):
    
    if month < 1 or month > 12:
        raise ValueError("Month must be between 1 and 12")
    
    query = f"""
    SELECT *
    FROM rental
    WHERE MONTH(rental_date) = {month}
      AND YEAR(rental_date) = {year}
    """
    
    return pd.read_sql(query, engine)

may_data = rentals_month(engine, 5, 2005)
may_data.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [9]:
# 3. Función rental_count_month que reciba el df de rentals_month y devuelva el # de alquileres por customer_id en ese mes y año

def rental_count_month(df, month, year):
    
    column_name = f"rentals_{month:02d}_{year}"
    
    return df.groupby("customer_id").size().reset_index(name=column_name)

may_count = rental_count_month(may_data, 5, 2005)
may_count.head()

   customer_id  rentals_05_2005
0            1                2
1            2                1
2            3                2
3            5                3
4            6                3

In [10]:
# 4. Función que compare 2 DataFrames (de dos meses distintos) y calcule la diferencia de alquileres por cliente
def compare_rentals(df1, df2):
    
    merged = pd.merge(df1, df2, on="customer_id", how="outer").fillna(0)
    
    may_col = df1.columns[1]
    jun_col = df2.columns[1]
    
    merged["difference"] = merged[jun_col] - merged[may_col]
    
    return merged

jun_data = rentals_month(engine, 6, 2005)
jun_count = rental_count_month(jun_data, 6, 2005)

comparison = compare_rentals(may_count, jun_count)
comparison.head()

   customer_id  rentals_05_2005  rentals_06_2005  difference
0            1              2.0              7.0         5.0
1            2              1.0              1.0         0.0
2            3              2.0              4.0         2.0
3            4              0.0              6.0         6.0
4            5              3.0              5.0         2.0